const demo={driver:{id:'ACVTC-ABJ-0001',pass:'1234',name:'Chauffeur Démo',section:'Abidjan'},admin:{id:'PRESIDENT',pass:'1234',name:'Président',role:'PRESIDENT'}};
function login(){const u=document.getElementById('user').value.trim(),p=document.getElementById('pass').value;let x=u===demo.driver.id&&p===demo.driver.pass?demo.driver:u===demo.admin.id&&p===demo.admin.pass?demo.admin:null;if(!x)return alert('Identifiant ou code incorrect');sessionStorage.setItem('acvtc',JSON.stringify(x));show(x)}
function logout(){sessionStorage.removeItem('acvtc');location.reload()}
function show(x){document.getElementById('login').classList.add('hide');document.getElementById('app').classList.remove('hide');document.getElementById('out').classList.remove('hide');const admin=x.role==='PRESIDENT';document.getElementById('nav').innerHTML=`<button onclick="home()">Tableau de bord</button><button onclick="card()">Carte membre</button><button onclick="dues()">Cotisations</button>${admin?'<button onclick="members()">Membres</button><button onclick="finance()">Finances</button>':''}`;home()}
function home(){document.getElementById('content').innerHTML=`<div class="grid"><div class="metric">Membres<b>1</b></div><div class="metric">Cotisation mensuelle<b>500 F</b></div><div class="metric">Retard après 2 semaines<b>+200 F</b></div></div><div class="card"><h2>ACVTC-CI</h2><p>Bienvenue dans la V1 de démonstration. Sections : Abidjan, Bouaké et Yamoussoukro.</p></div>`}
function card(){document.getElementById('content').innerHTML=`<div class="card"><h2>Carte numérique</h2><p><b>Matricule :</b> ACVTC-ABJ-0001</p><p><b>Section :</b> Abidjan</p><p><b>Statut :</b> Actif</p><p class="note">Le QR sécurisé sera relié au dossier membre dans la version avec base de données.</p></div>`}
function dues(){document.getElementById('content').innerHTML=`<div class="card"><h2>Cotisations</h2><table><tr><th>Mois</th><th>Montant</th><th>Statut</th></tr><tr><td>Août 2026</td><td>500 FCFA</td><td class="status">En attente</td></tr></table><p class="note">Après deux semaines de retard : pénalité unique de 200 FCFA, soit 700 FCFA.</p></div>`}
function members(){document.getElementById('content').innerHTML=`<div class="card"><h2>Gestion des membres</h2><p>Module de démonstration. La création et modification réelles seront activées avec la base de données.</p></div>`}
function finance(){document.getElementById('content').innerHTML=`<div class="card"><h2>Synthèse financière</h2><p>Cotisations, recettes et dépenses seront enregistrées avec journal d'audit dans la version connectée à la base.</p></div>`}
const saved=sessionStorage.getItem('acvtc');if(saved)show(JSON.parse(saved));
